#!/home/vlt-gui/env/bin/python2.7
# coding:utf-8

"""This file is part of Vulture 3.

Vulture 3 is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Vulture 3 is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Vulture 3.  If not, see http://www.gnu.org/licenses/.
"""
__author__     = "Kevin Guillemot"
__credits__    = []
__license__    = "GPLv3"
__version__    = "3.0.0"
__maintainer__ = "Vulture Project"
__email__      = "contact@vultureproject.org"
__doc__        = """This migration script update database for
logging into the MongoDB Internal Repository"""

import os
import sys

sys.path.append('/home/vlt-gui/vulture')
os.environ.setdefault("DJANGO_SETTINGS_MODULE", 'vulture.settings')

import django
django.setup()

from gui.models.system_settings import Cluster, LogAnalyserSettings, LogAnalyserRules

cluster = Cluster.objects.get()

loganalyser_settings = cluster.system_settings.loganalyser_settings

if not loganalyser_settings:
    loganalyser_settings = LogAnalyserSettings()
    cluster.system_settings.loganalyser_settings.loganalyser_rules = []

LOGANALYSER_DATABASES = [
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/alienvault_reputation.ipset', ["reputation"],
    "FireHol blocklist IPSets - alienvault_reputation "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/asprox_c2.ipset', ["malware"],
     "FireHol blocklist IPSets - asprox_c2 "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/atlas_attacks.ipset', ["attacks"],
     "FireHol blocklist IPSets - atlas_attacks "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/atlas_attacks_2d.ipset', ["attacks"],
     "FireHol blocklist IPSets - atlas_attacks_2d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/atlas_attacks_30d.ipset', ["attacks"],
     "FireHol blocklist IPSets - atlas_attacks_30d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/atlas_attacks_7d.ipset', ["attacks"],
     "FireHol blocklist IPSets - atlas_attacks_7d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/atlas_botnets.ipset', ["attacks"],
     "FireHol blocklist IPSets - atlas_botnets "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/atlas_botnets_2d.ipset', ["attacks"],
     "FireHol blocklist IPSets - atlas_botnets_2d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/atlas_botnets_30d.ipset', ["attacks"],
     "FireHol blocklist IPSets - atlas_botnets_30d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/atlas_botnets_7d.ipset', ["attacks"],
     "FireHol blocklist IPSets - atlas_botnets_7d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/atlas_fastflux.ipset', ["attacks"],
     "FireHol blocklist IPSets - atlas_fastflux "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/atlas_fastflux_2d.ipset', ["attacks"],
     "FireHol blocklist IPSets - atlas_fastflux_2d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/atlas_fastflux_30d.ipset', ["attacks"],
     "FireHol blocklist IPSets - atlas_fastflux_30d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/atlas_fastflux_7d.ipset', ["attacks"],
     "FireHol blocklist IPSets - atlas_fastflux_7d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/atlas_phishing.ipset', ["attacks"],
     "FireHol blocklist IPSets - atlas_phishing "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/atlas_phishing_2d.ipset', ["attacks"],
     "FireHol blocklist IPSets - atlas_phishing_2d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/atlas_phishing_30d.ipset', ["attacks"],
     "FireHol blocklist IPSets - atlas_phishing_30d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/atlas_phishing_7d.ipset', ["attacks"],
     "FireHol blocklist IPSets - atlas_phishing_7d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/atlas_scans.ipset', ["attacks"],
     "FireHol blocklist IPSets - atlas_scans "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/atlas_scans_2d.ipset', ["attacks"],
     "FireHol blocklist IPSets - atlas_scans_2d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/atlas_scans_30d.ipset', ["attacks"],
     "FireHol blocklist IPSets - atlas_scans_30d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/atlas_scans_7d.ipset', ["attacks"],
     "FireHol blocklist IPSets - atlas_scans_7d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bambenek_banjori.ipset', ["malware"],
     "FireHol blocklist IPSets - bambenek_banjori "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bambenek_bebloh.ipset', ["malware"],
     "FireHol blocklist IPSets - bambenek_bebloh "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bambenek_c2.ipset', ["malware"],
     "FireHol blocklist IPSets - bambenek_c2 "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bambenek_cl.ipset', ["malware"],
     "FireHol blocklist IPSets - bambenek_cl "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bambenek_cryptowall.ipset', ["malware"],
     "FireHol blocklist IPSets - bambenek_cryptowall "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bambenek_dircrypt.ipset', ["malware"],
     "FireHol blocklist IPSets - bambenek_dircrypt "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bambenek_dyre.ipset', ["malware"],
     "FireHol blocklist IPSets - bambenek_dyre "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bambenek_geodo.ipset', ["malware"],
     "FireHol blocklist IPSets - bambenek_geodo "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bambenek_hesperbot.ipset', ["malware"],
     "FireHol blocklist IPSets - bambenek_hesperbot "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bambenek_matsnu.ipset', ["malware"],
     "FireHol blocklist IPSets - bambenek_matsnu "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bambenek_necurs.ipset', ["malware"],
     "FireHol blocklist IPSets - bambenek_necurs "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bambenek_p2pgoz.ipset', ["malware"],
     "FireHol blocklist IPSets - bambenek_p2pgoz "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bambenek_pushdo.ipset', ["malware"],
     "FireHol blocklist IPSets - bambenek_pushdo "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bambenek_pykspa.ipset', ["malware"],
     "FireHol blocklist IPSets - bambenek_pykspa "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bambenek_qakbot.ipset', ["malware"],
     "FireHol blocklist IPSets - bambenek_qakbot "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bambenek_ramnit.ipset', ["malware"],
     "FireHol blocklist IPSets - bambenek_ramnit "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bambenek_ranbyus.ipset', ["malware"],
     "FireHol blocklist IPSets - bambenek_ranbyus "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bambenek_simda.ipset', ["malware"],
     "FireHol blocklist IPSets - bambenek_simda "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bambenek_suppobox.ipset', ["malware"],
     "FireHol blocklist IPSets - bambenek_suppobox "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bambenek_symmi.ipset', ["malware"],
     "FireHol blocklist IPSets - bambenek_symmi "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bambenek_tinba.ipset', ["malware"],
     "FireHol blocklist IPSets - bambenek_tinba "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bambenek_volatile.ipset', ["malware"],
     "FireHol blocklist IPSets - bambenek_volatile "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bbcan177_ms1.netset', ["malware"],
     "FireHol blocklist IPSets - bbcan177_ms1 "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bbcan177_ms3.netset', ["malware"],
     "FireHol blocklist IPSets - bbcan177_ms3 "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bds_atif.ipset', ["reputation"],
     "FireHol blocklist IPSets - bds_atif "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bi_any_2_1d.ipset', ["attacks"],
     "FireHol blocklist IPSets - bi_any_2_1d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bi_any_2_30d.ipset', ["attacks"],
     "FireHol blocklist IPSets - bi_any_2_30d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bi_any_2_7d.ipset', ["attacks"],
     "FireHol blocklist IPSets - bi_any_2_7d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bi_bruteforce_2_30d.ipset', ["attacks"],
     "FireHol blocklist IPSets - bi_bruteforce_2_30d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bi_ftp_2_30d.ipset', ["attacks"],
     "FireHol blocklist IPSets - bi_ftp_2_30d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bi_http_2_30d.ipset', ["attacks"],
     "FireHol blocklist IPSets - bi_http_2_30d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bi_mail_2_30d.ipset', ["attacks"],
     "FireHol blocklist IPSets - bi_mail_2_30d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bi_proxy_2_30d.ipset', ["attacks"],
     "FireHol blocklist IPSets - bi_proxy_2_30d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bi_sql_2_30d.ipset', ["attacks"],
     "FireHol blocklist IPSets - bi_sql_2_30d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bi_ssh_2_30d.ipset', ["attacks"],
     "FireHol blocklist IPSets - bi_ssh_2_30d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bi_voip_2_30d.ipset', ["attacks"],
     "FireHol blocklist IPSets - bi_voip_2_30d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bitcoin_blockchain_info.ipset', ["organizations"],
     "FireHol blocklist IPSets - bitcoin_blockchain_info "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bitcoin_blockchain_info_1d.ipset', ["organizations"],
    "FireHol blocklist IPSets - bitcoin_blockchain_info_1d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bitcoin_blockchain_info_30d.ipset',
     ["organizations"], "FireHol blocklist IPSets - bitcoin_blockchain_info_30d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bitcoin_blockchain_info_7d.ipset', ["organizations"],
    "FireHol blocklist IPSets - bitcoin_blockchain_info_7d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bitcoin_nodes.ipset', ["organizations"],
     "FireHol blocklist IPSets - bitcoin_nodes "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bitcoin_nodes_1d.ipset', ["organizations"],
     "FireHol blocklist IPSets - bitcoin_nodes_1d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bitcoin_nodes_30d.ipset', ["organizations"],
     "FireHol blocklist IPSets - bitcoin_nodes_30d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bitcoin_nodes_7d.ipset', ["organizations"],
     "FireHol blocklist IPSets - bitcoin_nodes_7d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/blocklist_de.ipset', ["attacks"],
     "FireHol blocklist IPSets - blocklist_de "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/blocklist_de_apache.ipset', ["attacks"],
     "FireHol blocklist IPSets - blocklist_de_apache "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/blocklist_de_bots.ipset', ["attacks"],
     "FireHol blocklist IPSets - blocklist_de_bots "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/blocklist_de_bruteforce.ipset', ["attacks"],
     "FireHol blocklist IPSets - blocklist_de_bruteforce "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/blocklist_de_ftp.ipset', ["attacks"],
     "FireHol blocklist IPSets - blocklist_de_ftp "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/blocklist_de_imap.ipset', ["attacks"],
     "FireHol blocklist IPSets - blocklist_de_imap "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/blocklist_de_mail.ipset', ["attacks"],
     "FireHol blocklist IPSets - blocklist_de_mail "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/blocklist_de_sip.ipset', ["attacks"],
     "FireHol blocklist IPSets - blocklist_de_sip "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/blocklist_de_ssh.ipset', ["attacks"],
     "FireHol blocklist IPSets - blocklist_de_ssh "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/blocklist_de_strongips.ipset', ["attacks"],
     "FireHol blocklist IPSets - blocklist_de_strongips "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/blocklist_net_ua.ipset', ["abuse"],
     "FireHol blocklist IPSets - blocklist_net_ua "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bm_tor.ipset', ["anonymizers"],
     "FireHol blocklist IPSets - bm_tor "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/botscout.ipset', ["abuse"],
     "FireHol blocklist IPSets - botscout "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/botscout_1d.ipset', ["abuse"],
     "FireHol blocklist IPSets - botscout_1d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/botscout_30d.ipset', ["abuse"],
     "FireHol blocklist IPSets - botscout_30d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/botscout_7d.ipset', ["abuse"],
     "FireHol blocklist IPSets - botscout_7d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/botvrij_dst.ipset', ["attacks"],
     "FireHol blocklist IPSets - botvrij_dst "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/botvrij_src.ipset', ["attacks"],
     "FireHol blocklist IPSets - botvrij_src "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/bruteforceblocker.ipset', ["attacks"],
     "FireHol blocklist IPSets - bruteforceblocker "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/chaosreigns_iprep0.ipset', ["spam"],
     "FireHol blocklist IPSets - chaosreigns_iprep0 "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/chaosreigns_iprep100.ipset', ["spam"],
     "FireHol blocklist IPSets - chaosreigns_iprep100 "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/chaosreigns_iprep50.ipset', ["spam"],
     "FireHol blocklist IPSets - chaosreigns_iprep50 "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/ciarmy.ipset', ["reputation"],
     "FireHol blocklist IPSets - ciarmy "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/cidr_report_bogons.netset', ["unrouteable"],
     "FireHol blocklist IPSets - cidr_report_bogons "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/cleanmx_phishing.ipset', ["spam"],
     "FireHol blocklist IPSets - cleanmx_phishing "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/cleanmx_viruses.ipset', ["spam"],
     "FireHol blocklist IPSets - cleanmx_viruses "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/cleantalk.ipset', ["abuse"],
     "FireHol blocklist IPSets - cleantalk "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/cleantalk_1d.ipset', ["abuse"],
     "FireHol blocklist IPSets - cleantalk_1d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/cleantalk_30d.ipset', ["abuse"],
     "FireHol blocklist IPSets - cleantalk_30d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/cleantalk_7d.ipset', ["abuse"],
     "FireHol blocklist IPSets - cleantalk_7d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/cleantalk_new.ipset', ["abuse"],
     "FireHol blocklist IPSets - cleantalk_new "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/cleantalk_new_1d.ipset', ["abuse"],
     "FireHol blocklist IPSets - cleantalk_new_1d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/cleantalk_new_30d.ipset', ["abuse"],
     "FireHol blocklist IPSets - cleantalk_new_30d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/cleantalk_new_7d.ipset', ["abuse"],
     "FireHol blocklist IPSets - cleantalk_new_7d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/cleantalk_top20.ipset', ["abuse"],
     "FireHol blocklist IPSets - cleantalk_top20 "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/cleantalk_updated.ipset', ["abuse"],
     "FireHol blocklist IPSets - cleantalk_updated "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/cleantalk_updated_1d.ipset', ["abuse"],
     "FireHol blocklist IPSets - cleantalk_updated_1d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/cleantalk_updated_30d.ipset', ["abuse"],
     "FireHol blocklist IPSets - cleantalk_updated_30d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/cleantalk_updated_7d.ipset', ["abuse"],
     "FireHol blocklist IPSets - cleantalk_updated_7d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/cruzit_web_attacks.ipset', ["attacks"],
     "FireHol blocklist IPSets - cruzit_web_attacks "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/cta_cryptowall.ipset', ["malware"],
     "FireHol blocklist IPSets - cta_cryptowall "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/cybercrime.ipset', ["malware"],
     "FireHol blocklist IPSets - cybercrime "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/darklist_de.netset', ["attacks"],
     "FireHol blocklist IPSets - darklist_de "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/dm_tor.ipset', ["anonymizers"],
     "FireHol blocklist IPSets - dm_tor "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/dshield.netset', ["attacks"],
     "FireHol blocklist IPSets - dshield "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/dshield_1d.netset', ["attacks"],
     "FireHol blocklist IPSets - dshield_1d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/dshield_30d.netset', ["attacks"],
     "FireHol blocklist IPSets - dshield_30d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/dshield_7d.netset', ["attacks"],
     "FireHol blocklist IPSets - dshield_7d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/dshield_top_1000.ipset', ["attacks"],
     "FireHol blocklist IPSets - dshield_top_1000 "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/dyndns_ponmocup.ipset', ["malware"],
     "FireHol blocklist IPSets - dyndns_ponmocup "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/esentire_14072015_com.ipset', ["malware"],
     "FireHol blocklist IPSets - esentire_14072015_com "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/esentire_14072015q_com.ipset', ["malware"],
     "FireHol blocklist IPSets - esentire_14072015q_com "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/esentire_22072014a_com.ipset', ["malware"],
     "FireHol blocklist IPSets - esentire_22072014a_com "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/esentire_22072014b_com.ipset', ["malware"],
     "FireHol blocklist IPSets - esentire_22072014b_com "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/esentire_22072014c_com.ipset', ["malware"],
     "FireHol blocklist IPSets - esentire_22072014c_com "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/esentire_atomictrivia_ru.ipset', ["malware"],
     "FireHol blocklist IPSets - esentire_atomictrivia_ru "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/esentire_auth_update_ru.ipset', ["malware"],
     "FireHol blocklist IPSets - esentire_auth_update_ru "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/esentire_crazyerror_su.ipset', ["malware"],
     "FireHol blocklist IPSets - esentire_crazyerror_su "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/esentire_dagestanskiiviskis_ru.ipset', ["malware"],
     "FireHol blocklist IPSets - esentire_dagestanskiiviskis_ru "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/esentire_differentia_ru.ipset', ["malware"],
     "FireHol blocklist IPSets - esentire_differentia_ru "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/esentire_disorderstatus_ru.ipset', ["malware"],
     "FireHol blocklist IPSets - esentire_disorderstatus_ru "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/esentire_dorttlokolrt_com.ipset', ["malware"],
     "FireHol blocklist IPSets - esentire_dorttlokolrt_com "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/esentire_downs1_ru.ipset', ["malware"],
     "FireHol blocklist IPSets - esentire_downs1_ru "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/esentire_ebankoalalusys_ru.ipset', ["malware"],
     "FireHol blocklist IPSets - esentire_ebankoalalusys_ru "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/esentire_emptyarray_ru.ipset', ["malware"],
     "FireHol blocklist IPSets - esentire_emptyarray_ru "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/esentire_fioartd_com.ipset', ["malware"],
     "FireHol blocklist IPSets - esentire_fioartd_com "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/esentire_getarohirodrons_com.ipset', ["malware"],
     "FireHol blocklist IPSets - esentire_getarohirodrons_com "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/esentire_hasanhashsde_ru.ipset', ["malware"],
     "FireHol blocklist IPSets - esentire_hasanhashsde_ru "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/esentire_inleet_ru.ipset', ["malware"],
     "FireHol blocklist IPSets - esentire_inleet_ru "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/esentire_islamislamdi_ru.ipset', ["malware"],
     "FireHol blocklist IPSets - esentire_islamislamdi_ru "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/esentire_krnqlwlplttc_com.ipset', ["malware"],
     "FireHol blocklist IPSets - esentire_krnqlwlplttc_com "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/esentire_maddox1_ru.ipset', ["malware"],
     "FireHol blocklist IPSets - esentire_maddox1_ru "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/esentire_manning1_ru.ipset', ["malware"],
     "FireHol blocklist IPSets - esentire_manning1_ru "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/esentire_misteryherson_ru.ipset', ["malware"],
     "FireHol blocklist IPSets - esentire_misteryherson_ru "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/esentire_mysebstarion_ru.ipset', ["malware"],
     "FireHol blocklist IPSets - esentire_mysebstarion_ru "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/esentire_smartfoodsglutenfree_kz.ipset', ["malware"],
    "FireHol blocklist IPSets - esentire_smartfoodsglutenfree_kz "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/esentire_venerologvasan93_ru.ipset', ["malware"],
     "FireHol blocklist IPSets - esentire_venerologvasan93_ru "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/esentire_volaya_ru.ipset', ["malware"],
     "FireHol blocklist IPSets - esentire_volaya_ru "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/et_block.netset', ["attacks"],
     "FireHol blocklist IPSets - et_block "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/et_botcc.ipset', ["reputation"],
     "FireHol blocklist IPSets - et_botcc "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/et_compromised.ipset', ["attacks"],
     "FireHol blocklist IPSets - et_compromised "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/et_dshield.netset', ["attacks"],
     "FireHol blocklist IPSets - et_dshield "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/et_spamhaus.netset', ["attacks"],
     "FireHol blocklist IPSets - et_spamhaus "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/et_tor.ipset', ["anonymizers"],
     "FireHol blocklist IPSets - et_tor "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/feodo.ipset', ["malware"],
     "FireHol blocklist IPSets - feodo "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/feodo_badips.ipset', ["malware"],
     "FireHol blocklist IPSets - feodo_badips "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/firehol_abusers_1d.netset', ["abuse"],
     "FireHol blocklist IPSets - firehol_abusers_1d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/firehol_abusers_30d.netset', ["abuse"],
     "FireHol blocklist IPSets - firehol_abusers_30d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/firehol_anonymous.netset', ["anonymizers"],
     "FireHol blocklist IPSets - firehol_anonymous "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/firehol_level1.netset', ["attacks"],
     "FireHol blocklist IPSets - firehol_level1 "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/firehol_level2.netset', ["attacks"],
     "FireHol blocklist IPSets - firehol_level2 "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/firehol_level3.netset', ["attacks"],
     "FireHol blocklist IPSets - firehol_level3 "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/firehol_level4.netset', ["attacks"],
     "FireHol blocklist IPSets - firehol_level4 "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/firehol_proxies.netset', ["anonymizers"],
     "FireHol blocklist IPSets - firehol_proxies "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/firehol_webclient.netset', ["malware"],
     "FireHol blocklist IPSets - firehol_webclient "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/firehol_webserver.netset', ["attacks"],
     "FireHol blocklist IPSets - firehol_webserver "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/gofferje_sip.netset', ["attacks"],
     "FireHol blocklist IPSets - gofferje_sip "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/gpf_comics.ipset', ["abuse"],
     "FireHol blocklist IPSets - gpf_comics "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/graphiclineweb.netset', ["abuse"],
     "FireHol blocklist IPSets - graphiclineweb "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/greensnow.ipset', ["attacks"],
     "FireHol blocklist IPSets - greensnow "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/haley_ssh.ipset', ["attacks"],
     "FireHol blocklist IPSets - haley_ssh "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/hphosts_ats.ipset', ["organizations"],
     "FireHol blocklist IPSets - hphosts_ats "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/hphosts_emd.ipset', ["malware"],
     "FireHol blocklist IPSets - hphosts_emd "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/hphosts_exp.ipset', ["malware"],
     "FireHol blocklist IPSets - hphosts_exp "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/hphosts_fsa.ipset', ["reputation"],
     "FireHol blocklist IPSets - hphosts_fsa "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/hphosts_grm.ipset', ["spam"],
     "FireHol blocklist IPSets - hphosts_grm "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/hphosts_hfs.ipset', ["abuse"],
     "FireHol blocklist IPSets - hphosts_hfs "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/hphosts_hjk.ipset', ["malware"],
     "FireHol blocklist IPSets - hphosts_hjk "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/hphosts_mmt.ipset', ["reputation"],
     "FireHol blocklist IPSets - hphosts_mmt "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/hphosts_pha.ipset', ["reputation"],
     "FireHol blocklist IPSets - hphosts_pha "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/hphosts_psh.ipset', ["reputation"],
     "FireHol blocklist IPSets - hphosts_psh "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/hphosts_wrz.ipset', ["reputation"],
     "FireHol blocklist IPSets - hphosts_wrz "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/iblocklist_abuse_palevo.netset', ["malware"],
     "FireHol blocklist IPSets - iblocklist_abuse_palevo "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/iblocklist_abuse_spyeye.netset', ["malware"],
     "FireHol blocklist IPSets - iblocklist_abuse_spyeye "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/iblocklist_abuse_zeus.netset', ["malware"],
     "FireHol blocklist IPSets - iblocklist_abuse_zeus "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/iblocklist_ciarmy_malicious.netset', ["reputation"],
     "FireHol blocklist IPSets - iblocklist_ciarmy_malicious "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/iblocklist_cidr_report_bogons.netset',
     ["unrouteable"], "FireHol blocklist IPSets - iblocklist_cidr_report_bogons "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/iblocklist_cruzit_web_attacks.netset', ["attacks"],
     "FireHol blocklist IPSets - iblocklist_cruzit_web_attacks "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/iblocklist_isp_aol.netset', ["organizations"],
     "FireHol blocklist IPSets - iblocklist_isp_aol "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/iblocklist_isp_att.netset', ["organizations"],
     "FireHol blocklist IPSets - iblocklist_isp_att "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/iblocklist_isp_cablevision.netset',
     ["organizations"], "FireHol blocklist IPSets - iblocklist_isp_cablevision "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/iblocklist_isp_charter.netset', ["organizations"],
     "FireHol blocklist IPSets - iblocklist_isp_charter "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/iblocklist_isp_comcast.netset', ["organizations"],
     "FireHol blocklist IPSets - iblocklist_isp_comcast "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/iblocklist_isp_embarq.netset', ["organizations"],
     "FireHol blocklist IPSets - iblocklist_isp_embarq "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/iblocklist_isp_qwest.netset', ["organizations"],
     "FireHol blocklist IPSets - iblocklist_isp_qwest "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/iblocklist_isp_sprint.netset', ["organizations"],
     "FireHol blocklist IPSets - iblocklist_isp_sprint "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/iblocklist_isp_suddenlink.netset', ["organizations"],
    "FireHol blocklist IPSets - iblocklist_isp_suddenlink "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/iblocklist_isp_twc.netset', ["organizations"],
     "FireHol blocklist IPSets - iblocklist_isp_twc "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/iblocklist_isp_verizon.netset', ["organizations"],
     "FireHol blocklist IPSets - iblocklist_isp_verizon "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/iblocklist_malc0de.netset', ["malware"],
     "FireHol blocklist IPSets - iblocklist_malc0de "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/iblocklist_onion_router.netset', ["anonymizers"],
     "FireHol blocklist IPSets - iblocklist_onion_router "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/iblocklist_org_activision.netset', ["organizations"],
    "FireHol blocklist IPSets - iblocklist_org_activision "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/iblocklist_org_apple.netset', ["organizations"],
     "FireHol blocklist IPSets - iblocklist_org_apple "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/iblocklist_org_blizzard.netset', ["organizations"],
     "FireHol blocklist IPSets - iblocklist_org_blizzard "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/iblocklist_org_crowd_control.netset',
     ["organizations"], "FireHol blocklist IPSets - iblocklist_org_crowd_control "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/iblocklist_org_electronic_arts.netset',
     ["organizations"], "FireHol blocklist IPSets - iblocklist_org_electronic_arts "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/iblocklist_org_joost.netset', ["organizations"],
     "FireHol blocklist IPSets - iblocklist_org_joost "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/iblocklist_org_linden_lab.netset', ["organizations"],
    "FireHol blocklist IPSets - iblocklist_org_linden_lab "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/iblocklist_org_logmein.netset', ["organizations"],
     "FireHol blocklist IPSets - iblocklist_org_logmein "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/iblocklist_org_ncsoft.netset', ["organizations"],
     "FireHol blocklist IPSets - iblocklist_org_ncsoft "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/iblocklist_org_nintendo.netset', ["organizations"],
     "FireHol blocklist IPSets - iblocklist_org_nintendo "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/iblocklist_org_pandora.netset', ["organizations"],
     "FireHol blocklist IPSets - iblocklist_org_pandora "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/iblocklist_org_pirate_bay.netset', ["organizations"],
    "FireHol blocklist IPSets - iblocklist_org_pirate_bay "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/iblocklist_org_punkbuster.netset', ["organizations"],
    "FireHol blocklist IPSets - iblocklist_org_punkbuster "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/iblocklist_org_riot_games.netset', ["organizations"],
    "FireHol blocklist IPSets - iblocklist_org_riot_games "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/iblocklist_org_sony_online.netset',
     ["organizations"], "FireHol blocklist IPSets - iblocklist_org_sony_online "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/iblocklist_org_square_enix.netset',
     ["organizations"], "FireHol blocklist IPSets - iblocklist_org_square_enix "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/iblocklist_org_steam.netset', ["organizations"],
     "FireHol blocklist IPSets - iblocklist_org_steam "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/iblocklist_org_ubisoft.netset', ["organizations"],
     "FireHol blocklist IPSets - iblocklist_org_ubisoft "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/iblocklist_org_xfire.netset', ["organizations"],
     "FireHol blocklist IPSets - iblocklist_org_xfire "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/iblocklist_pedophiles.netset', ["reputation"],
     "FireHol blocklist IPSets - iblocklist_pedophiles "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/iblocklist_spamhaus_drop.netset', ["attacks"],
     "FireHol blocklist IPSets - iblocklist_spamhaus_drop "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/iblocklist_yoyo_adservers.netset', ["organizations"],
    "FireHol blocklist IPSets - iblocklist_yoyo_adservers "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/ipblacklistcloud_recent.ipset', ["abuse"],
     "FireHol blocklist IPSets - ipblacklistcloud_recent "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/ipblacklistcloud_recent_1d.ipset', ["abuse"],
     "FireHol blocklist IPSets - ipblacklistcloud_recent_1d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/ipblacklistcloud_recent_30d.ipset', ["abuse"],
     "FireHol blocklist IPSets - ipblacklistcloud_recent_30d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/ipblacklistcloud_recent_7d.ipset', ["abuse"],
     "FireHol blocklist IPSets - ipblacklistcloud_recent_7d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/ipblacklistcloud_top.ipset', ["abuse"],
     "FireHol blocklist IPSets - ipblacklistcloud_top "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/iw_spamlist.ipset', ["spam"],
     "FireHol blocklist IPSets - iw_spamlist "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/iw_wormlist.ipset', ["spam"],
     "FireHol blocklist IPSets - iw_wormlist "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/jigsaw_attacks.ipset', ["attacks"],
     "FireHol blocklist IPSets - jigsaw_attacks "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/jigsaw_malware.ipset', ["malware"],
     "FireHol blocklist IPSets - jigsaw_malware "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/lashback_ubl.ipset', ["spam"],
     "FireHol blocklist IPSets - lashback_ubl "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/malc0de.ipset', ["malware"],
     "FireHol blocklist IPSets - malc0de "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/malwaredomainlist.ipset', ["malware"],
     "FireHol blocklist IPSets - malwaredomainlist "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/maxmind_proxy_fraud.ipset', ["anonymizers"],
     "FireHol blocklist IPSets - maxmind_proxy_fraud "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/myip.ipset', ["abuse"],
     "FireHol blocklist IPSets - myip "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/nixspam.ipset', ["spam"],
     "FireHol blocklist IPSets - nixspam "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/nt_malware_dns.ipset', ["attacks"],
     "FireHol blocklist IPSets - nt_malware_dns "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/nt_malware_http.ipset', ["attacks"],
     "FireHol blocklist IPSets - nt_malware_http "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/nt_malware_irc.ipset', ["attacks"],
     "FireHol blocklist IPSets - nt_malware_irc "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/nt_ssh_7d.ipset', ["attacks"],
     "FireHol blocklist IPSets - nt_ssh_7d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/nullsecure.ipset', ["reputation"],
     "FireHol blocklist IPSets - nullsecure "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/openbl_180d.ipset', ["attacks"],
     "FireHol blocklist IPSets - openbl_180d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/openbl_1d.ipset', ["attacks"],
     "FireHol blocklist IPSets - openbl_1d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/openbl_30d.ipset', ["attacks"],
     "FireHol blocklist IPSets - openbl_30d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/openbl_360d.ipset', ["attacks"],
     "FireHol blocklist IPSets - openbl_360d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/openbl_60d.ipset', ["attacks"],
     "FireHol blocklist IPSets - openbl_60d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/openbl_7d.ipset', ["attacks"],
     "FireHol blocklist IPSets - openbl_7d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/openbl_90d.ipset', ["attacks"],
     "FireHol blocklist IPSets - openbl_90d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/openbl_all.ipset', ["attacks"],
     "FireHol blocklist IPSets - openbl_all "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/packetmail.ipset', ["reputation"],
     "FireHol blocklist IPSets - packetmail "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/packetmail_carisirt.ipset', ["reputation"],
     "FireHol blocklist IPSets - packetmail_carisirt "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/packetmail_emerging_ips.ipset', ["reputation"],
     "FireHol blocklist IPSets - packetmail_emerging_ips "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/packetmail_mail.ipset', ["reputation"],
     "FireHol blocklist IPSets - packetmail_mail "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/packetmail_ramnode.ipset', ["reputation"],
     "FireHol blocklist IPSets - packetmail_ramnode "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/palevo.ipset', ["malware"],
     "FireHol blocklist IPSets - palevo "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/php_commenters.ipset', ["spam"],
     "FireHol blocklist IPSets - php_commenters "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/php_commenters_1d.ipset', ["spam"],
     "FireHol blocklist IPSets - php_commenters_1d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/php_commenters_30d.ipset', ["spam"],
     "FireHol blocklist IPSets - php_commenters_30d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/php_commenters_7d.ipset', ["spam"],
     "FireHol blocklist IPSets - php_commenters_7d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/php_dictionary.ipset', ["spam"],
     "FireHol blocklist IPSets - php_dictionary "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/php_dictionary_1d.ipset', ["spam"],
     "FireHol blocklist IPSets - php_dictionary_1d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/php_dictionary_30d.ipset', ["spam"],
     "FireHol blocklist IPSets - php_dictionary_30d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/php_dictionary_7d.ipset', ["spam"],
     "FireHol blocklist IPSets - php_dictionary_7d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/php_harvesters.ipset', ["spam"],
     "FireHol blocklist IPSets - php_harvesters "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/php_harvesters_1d.ipset', ["spam"],
     "FireHol blocklist IPSets - php_harvesters_1d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/php_harvesters_30d.ipset', ["spam"],
     "FireHol blocklist IPSets - php_harvesters_30d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/php_harvesters_7d.ipset', ["spam"],
     "FireHol blocklist IPSets - php_harvesters_7d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/php_spammers.ipset', ["spam"],
     "FireHol blocklist IPSets - php_spammers "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/php_spammers_1d.ipset', ["spam"],
     "FireHol blocklist IPSets - php_spammers_1d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/php_spammers_30d.ipset', ["spam"],
     "FireHol blocklist IPSets - php_spammers_30d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/php_spammers_7d.ipset', ["spam"],
     "FireHol blocklist IPSets - php_spammers_7d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/proxylists.ipset', ["anonymizers"],
     "FireHol blocklist IPSets - proxylists "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/proxylists_1d.ipset', ["anonymizers"],
     "FireHol blocklist IPSets - proxylists_1d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/proxylists_30d.ipset', ["anonymizers"],
     "FireHol blocklist IPSets - proxylists_30d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/proxylists_7d.ipset', ["anonymizers"],
     "FireHol blocklist IPSets - proxylists_7d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/proxyrss.ipset', ["anonymizers"],
     "FireHol blocklist IPSets - proxyrss "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/proxyrss_1d.ipset', ["anonymizers"],
     "FireHol blocklist IPSets - proxyrss_1d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/proxyrss_30d.ipset', ["anonymizers"],
     "FireHol blocklist IPSets - proxyrss_30d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/proxyrss_7d.ipset', ["anonymizers"],
     "FireHol blocklist IPSets - proxyrss_7d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/proxyspy.ipset', ["anonymizers"],
     "FireHol blocklist IPSets - proxyspy "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/proxyspy_1d.ipset', ["anonymizers"],
     "FireHol blocklist IPSets - proxyspy_1d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/proxyspy_30d.ipset', ["anonymizers"],
     "FireHol blocklist IPSets - proxyspy_30d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/proxyspy_7d.ipset', ["anonymizers"],
     "FireHol blocklist IPSets - proxyspy_7d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/proxz.ipset', ["anonymizers"],
     "FireHol blocklist IPSets - proxz "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/proxz_1d.ipset', ["anonymizers"],
     "FireHol blocklist IPSets - proxz_1d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/proxz_30d.ipset', ["anonymizers"],
     "FireHol blocklist IPSets - proxz_30d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/proxz_7d.ipset', ["anonymizers"],
     "FireHol blocklist IPSets - proxz_7d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/pushing_inertia_blocklist.netset', ["reputation"],
     "FireHol blocklist IPSets - pushing_inertia_blocklist "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/ransomware_cryptowall_ps.ipset', ["malware"],
     "FireHol blocklist IPSets - ransomware_cryptowall_ps "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/ransomware_feed.ipset', ["malware"],
     "FireHol blocklist IPSets - ransomware_feed "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/ransomware_locky_c2.ipset', ["malware"],
     "FireHol blocklist IPSets - ransomware_locky_c2 "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/ransomware_locky_ps.ipset', ["malware"],
     "FireHol blocklist IPSets - ransomware_locky_ps "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/ransomware_online.ipset', ["malware"],
     "FireHol blocklist IPSets - ransomware_online "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/ransomware_rw.ipset', ["malware"],
     "FireHol blocklist IPSets - ransomware_rw "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/ransomware_teslacrypt_ps.ipset', ["malware"],
     "FireHol blocklist IPSets - ransomware_teslacrypt_ps "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/ransomware_torrentlocker_c2.ipset', ["malware"],
     "FireHol blocklist IPSets - ransomware_torrentlocker_c2 "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/ransomware_torrentlocker_ps.ipset', ["malware"],
     "FireHol blocklist IPSets - ransomware_torrentlocker_ps "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/ri_connect_proxies.ipset', ["anonymizers"],
     "FireHol blocklist IPSets - ri_connect_proxies "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/ri_connect_proxies_1d.ipset', ["anonymizers"],
     "FireHol blocklist IPSets - ri_connect_proxies_1d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/ri_connect_proxies_30d.ipset', ["anonymizers"],
     "FireHol blocklist IPSets - ri_connect_proxies_30d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/ri_connect_proxies_7d.ipset', ["anonymizers"],
     "FireHol blocklist IPSets - ri_connect_proxies_7d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/ri_web_proxies.ipset', ["anonymizers"],
     "FireHol blocklist IPSets - ri_web_proxies "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/ri_web_proxies_1d.ipset', ["anonymizers"],
     "FireHol blocklist IPSets - ri_web_proxies_1d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/ri_web_proxies_30d.ipset', ["anonymizers"],
     "FireHol blocklist IPSets - ri_web_proxies_30d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/ri_web_proxies_7d.ipset', ["anonymizers"],
     "FireHol blocklist IPSets - ri_web_proxies_7d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/sblam.ipset', ["abuse"],
     "FireHol blocklist IPSets - sblam "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/set_file_timestamps.sh', [""],
     "FireHol blocklist IPSets - set_file_timestamps "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/shunlist.ipset', ["attacks"],
     "FireHol blocklist IPSets - shunlist "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/snort_ipfilter.ipset', ["attacks"],
     "FireHol blocklist IPSets - snort_ipfilter "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/socks_proxy.ipset', ["anonymizers"],
     "FireHol blocklist IPSets - socks_proxy "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/socks_proxy_1d.ipset', ["anonymizers"],
     "FireHol blocklist IPSets - socks_proxy_1d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/socks_proxy_30d.ipset', ["anonymizers"],
     "FireHol blocklist IPSets - socks_proxy_30d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/socks_proxy_7d.ipset', ["anonymizers"],
     "FireHol blocklist IPSets - socks_proxy_7d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/sp_anti_infringement.netset', ["organizations"],
     "FireHol blocklist IPSets - sp_anti_infringement "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/sp_atma.netset', ["attacks"],
     "FireHol blocklist IPSets - sp_atma "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/sp_spammers.netset', ["spam"],
     "FireHol blocklist IPSets - sp_spammers "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/spamhaus_drop.netset', ["reputation"],
     "FireHol blocklist IPSets - spamhaus_drop "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/spamhaus_edrop.netset', ["reputation"],
     "FireHol blocklist IPSets - spamhaus_edrop "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/sslbl.ipset', ["malware"],
     "FireHol blocklist IPSets - sslbl "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/sslbl_aggressive.ipset', ["malware"],
     "FireHol blocklist IPSets - sslbl_aggressive "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/sslproxies.ipset', ["anonymizers"],
     "FireHol blocklist IPSets - sslproxies "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/sslproxies_1d.ipset', ["anonymizers"],
     "FireHol blocklist IPSets - sslproxies_1d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/sslproxies_30d.ipset', ["anonymizers"],
     "FireHol blocklist IPSets - sslproxies_30d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/sslproxies_7d.ipset', ["anonymizers"],
     "FireHol blocklist IPSets - sslproxies_7d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/stopforumspam.ipset', ["abuse"],
     "FireHol blocklist IPSets - stopforumspam "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/stopforumspam_180d.ipset', ["abuse"],
     "FireHol blocklist IPSets - stopforumspam_180d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/stopforumspam_1d.ipset', ["abuse"],
     "FireHol blocklist IPSets - stopforumspam_1d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/stopforumspam_30d.ipset', ["abuse"],
     "FireHol blocklist IPSets - stopforumspam_30d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/stopforumspam_365d.ipset', ["abuse"],
     "FireHol blocklist IPSets - stopforumspam_365d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/stopforumspam_7d.ipset', ["abuse"],
     "FireHol blocklist IPSets - stopforumspam_7d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/stopforumspam_90d.ipset', ["abuse"],
     "FireHol blocklist IPSets - stopforumspam_90d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/stopforumspam_toxic.netset', ["abuse"],
     "FireHol blocklist IPSets - stopforumspam_toxic "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/taichung.ipset', ["attacks"],
     "FireHol blocklist IPSets - taichung "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/talosintel_ipfilter.ipset', ["attacks"],
     "FireHol blocklist IPSets - talosintel_ipfilter "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/threatcrowd.ipset', ["malware"],
     "FireHol blocklist IPSets - threatcrowd "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/tor_exits.ipset', ["anonymizers"],
     "FireHol blocklist IPSets - tor_exits "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/tor_exits_1d.ipset', ["anonymizers"],
     "FireHol blocklist IPSets - tor_exits_1d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/tor_exits_30d.ipset', ["anonymizers"],
     "FireHol blocklist IPSets - tor_exits_30d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/tor_exits_7d.ipset', ["anonymizers"],
     "FireHol blocklist IPSets - tor_exits_7d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/trustedsec_atif.ipset', ["reputation"],
     "FireHol blocklist IPSets - trustedsec_atif "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/turris_greylist.ipset', ["reputation"],
     "FireHol blocklist IPSets - turris_greylist "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/urandomusto_dns.ipset', ["attacks"],
     "FireHol blocklist IPSets - urandomusto_dns "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/urandomusto_ftp.ipset', ["attacks"],
     "FireHol blocklist IPSets - urandomusto_ftp "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/urandomusto_http.ipset', ["attacks"],
     "FireHol blocklist IPSets - urandomusto_http "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/urandomusto_mailer.ipset', ["spam"],
     "FireHol blocklist IPSets - urandomusto_mailer "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/urandomusto_malware.ipset', ["malware"],
     "FireHol blocklist IPSets - urandomusto_malware "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/urandomusto_ntp.ipset', ["attacks"],
     "FireHol blocklist IPSets - urandomusto_ntp "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/urandomusto_rdp.ipset', ["attacks"],
     "FireHol blocklist IPSets - urandomusto_rdp "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/urandomusto_smb.ipset', ["attacks"],
     "FireHol blocklist IPSets - urandomusto_smb "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/urandomusto_spam.ipset', ["spam"],
     "FireHol blocklist IPSets - urandomusto_spam "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/urandomusto_ssh.ipset', ["attacks"],
     "FireHol blocklist IPSets - urandomusto_ssh "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/urandomusto_telnet.ipset', ["attacks"],
     "FireHol blocklist IPSets - urandomusto_telnet "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/urandomusto_unspecified.ipset', ["attacks"],
     "FireHol blocklist IPSets - urandomusto_unspecified "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/urandomusto_vnc.ipset', ["attacks"],
     "FireHol blocklist IPSets - urandomusto_vnc "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/urlvir.ipset', ["malware"],
     "FireHol blocklist IPSets - urlvir "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/virbl.ipset', ["spam"],
     "FireHol blocklist IPSets - virbl "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/voipbl.netset', ["attacks"],
     "FireHol blocklist IPSets - voipbl "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/vxvault.ipset', ["malware"],
     "FireHol blocklist IPSets - vxvault "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/xforce_bccs.ipset', ["malware"],
     "FireHol blocklist IPSets - xforce_bccs "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/xroxy.ipset', ["anonymizers"],
     "FireHol blocklist IPSets - xroxy "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/xroxy_1d.ipset', ["anonymizers"],
     "FireHol blocklist IPSets - xroxy_1d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/xroxy_30d.ipset', ["anonymizers"],
     "FireHol blocklist IPSets - xroxy_30d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/xroxy_7d.ipset', ["anonymizers"],
     "FireHol blocklist IPSets - xroxy_7d "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/yoyo_adservers.ipset', ["organizations"],
     "FireHol blocklist IPSets - yoyo_adservers "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/zeus.ipset', ["malware"],
     "FireHol blocklist IPSets - zeus "),
    ('https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/zeus_badips.ipset', ["malware"],
     "FireHol blocklist IPSets - zeus_badips ")
]

for rule in LOGANALYSER_DATABASES:
    loganalyser_settings.loganalyser_rules.append(LogAnalyserRules(**{
        'url': rule[0],
        'description': rule[2],
        'tags': ",".join(rule[1])
    }))

cluster.system_settings.loganalyser_settings = loganalyser_settings
cluster.save()

